# Prow Plugins Configuration for BHV (Behavioral Health Vault)
# This file configures bot commands for managing issues and pull requests

# Plugin configuration applies to all repos in the organization
# Adjust the repo paths according to your GitHub organization structure
plugins:
  KathiraveluLab/BHV:
    # Core plugins for PR and issue management
    plugins:
      # Trigger plugin - handles /test and /retest commands
      - trigger

      # Approve plugin - handles /approve command
      - approve

      # LGTM plugin - handles /lgtm command
      - lgtm

      # Hold plugin - handles /hold and /unhold commands
      - hold

      # Label plugin - handles /kind, /priority, /area commands
      - label

      # Assign plugin - handles /assign and /unassign commands
      - assign

      # Lifecycle plugin - handles /close and /reopen commands
      - lifecycle

      # Size plugin - automatically labels PRs by size
      - size

      # Welcome plugin - welcomes new contributors
      - welcome

      # Help plugin - provides help about available commands
      - help

      # Cat and dog plugins - fun commands for morale
      - cat
      - dog

      # Wip plugin - marks PRs with WIP status
      - wip

      # Require-matching-label - enforce labels before merge
      - require-matching-label

      # Override plugin - allows bypassing certain checks
      - override

      # Retitle plugin - allows updating PR titles
      - retitle

      # Milestone plugin - handles milestone management
      - milestone

# External plugins (custom plugins specific to Python workflows)
external_plugins:
  KathiraveluLab/BHV:
    - name: needs-info
      events:
        - issue_comment
        - pull_request_review_comment

# Approve plugin configuration
approve:
  - repos:
      - KathiraveluLab/BHV
    # Require approval from someone other than PR author
    require_self_approval: false
    # Number of approvals needed
    lgtm_acts_as_approve: false
    # Ignore review state and only check for /approve
    ignore_review_state: false

# LGTM plugin configuration
lgtm:
  - repos:
      - KathiraveluLab/BHV
    # Reviews with "lgtm" in the body count as /lgtm
    review_acts_as_lgtm: true
    # Allow authors to /lgtm their own PRs (generally not recommended)
    store_tree_hash: true
    # Remove lgtm label when PR is updated
    sticky_lgtm_team: ""

# Label plugin configuration
label:
  additional_labels:
    # Issue types (used with /kind command)
    - kind/bug
    - kind/feature
    - kind/enhancement
    - kind/documentation
    - kind/question
    - kind/cleanup
    - kind/security
    - kind/performance

    # Priority levels (used with /priority command)
    - priority/p0 # Critical
    - priority/p1 # High
    - priority/p2 # Medium
    - priority/p3 # Low

    # Area labels (used with /area command)
    - area/api
    - area/auth
    - area/database
    - area/frontend
    - area/storage
    - area/testing
    - area/ci-cd
    - area/documentation
    - area/security

    # Lifecycle labels
    - lifecycle/frozen
    - lifecycle/stale
    - lifecycle/rotten

    # Status labels
    - needs-info
    - needs-rebase
    - needs-ok-to-test
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - do-not-merge/invalid-owners-file

    # Merge ready labels
    - lgtm
    - approved

    # Help wanted labels
    - good-first-issue
    - help-wanted

    # Python specific labels
    - python/lint
    - python/format
    - python/typing
    - python/tests

# Size plugin configuration (automatically labels PRs by lines changed)
size:
  s: 10 # 0-10 lines
  m: 30 # 11-30 lines
  l: 100 # 31-100 lines
  xl: 500 # 101-500 lines
  xxl: 1000 # 501-1000 lines

# Welcome plugin configuration
welcome:
  - repos:
      - KathiraveluLab/BHV
    message_template: |
      Welcome @{{.AuthorLogin}}!

      Thank you for your contribution to BHV (Behavioral Health Vault)!

      {% if .IsPR %}
      A few things to help you get started:
      - Make sure you've read our [Contributing Guide](https://github.com/KathiraveluLab/BHV/blob/main/CONTRIBUTING.md)
      - Check that all CI tests pass
      - A maintainer will review your PR soon

      Available commands you can use:
      - `/retest` - Rerun failing tests
      - `/ready` - Mark PR as ready for review
      - Comment `/help` to see all available commands
      {% else %}
      Thank you for opening an issue!

      A maintainer will review your issue and respond as soon as possible.

      In the meantime, you can:
      - Add more details if needed
      - Use `/kind <type>` to categorize your issue (bug, feature, docs, question)
      - Comment `/help` to see all available commands
      {% endif %}

# Require matching label configuration
require_matching_label:
  - missing_label: needs-kind
    org: KathiraveluLab
    repo: BHV
    # PRs must have a kind/* label
    prs: true
    regexp: ^kind/
    # Friendly message when label is missing
    missing_comment: |
      This PR needs a `kind/*` label to indicate what type of change it is.

      Please use one of these commands:
      - `/kind bug` - Bug fix
      - `/kind feature` - New feature
      - `/kind enhancement` - Enhancement to existing feature
      - `/kind documentation` - Documentation update
      - `/kind cleanup` - Code cleanup/refactoring
      - `/kind security` - Security fix

# Trigger plugin configuration (for /test and /retest commands)
triggers:
  - repos:
      - KathiraveluLab/BHV
    # Only org members can trigger tests by default
    only_org_members: true
    # Allow /ok-to-test from org members to allow external contributors to run tests
    trusted_org: KathiraveluLab
    # Join org URL for contributors
    join_org_url: "https://github.com/KathiraveluLab"

# Configure which groups can use which commands
config_updater:
  maps:
    prow/plugins.yaml:
      name: plugins
    prow/config.yaml:
      name: config

# Owners configuration
owners:
  # Use OWNERS files for approval
  mdyamlrepos:
    - KathiraveluLab/BHV
  # Skip collaborators check (useful for private repos)
  skip_collaborators:
    - KathiraveluLab/BHV

# Blockades - prevent certain actions
blockades:
  - repos:
      - KathiraveluLab/BHV
    blockregexps:
      # Block merging PRs with certain labels
      - re: "^do-not-merge"
        explanation: "This PR is marked as 'do-not-merge'. Remove the label to proceed."

# Milestone applier - automatically apply milestones
repo_milestone:
  KathiraveluLab/BHV:
    # Maintainers team can manage milestones
    maintainers_id: 0 # Replace with your GitHub team ID
    maintainers_team: maintainers
    maintainers_friendly_name: Maintainers

# Override plugin configuration
override:
  allow_top_level_owners: true

# Heart plugin - react with heart emoji to certain events
heart:
  adorees:
    - KathiraveluLab

# Slack reporter configuration (optional - configure if you use Slack)
# slack:
#   mergewarnings:
#     - repos:
#         - KathiraveluLab/BHV
#       channels:
#         - bhv-dev
#       whitelist:
#         - approved

# Branch protection requirements
branch-protection-requirements:
  orgs:
    KathiraveluLab:
      repos:
        BHV:
          branches:
            main:
              protect: true
              required_status_checks:
                contexts:
                  - "continuous-integration/jenkins/pr-merge"
                  - "Python Lint"
                  - "Python Tests"
            dev:
              protect: true
              required_status_checks:
                contexts:
                  - "Python Lint"
